# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-03 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaApp', '0003_auto_20200103_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='iprofile',
        ),
    ]
